### ISSUE TITLE
ESM types are wrong

### ISSUE THREAD

**Issue by wooorm** [remarkablemark/style-to-object#205]
## Expected Behavior

Be able to use the default normally from ESM.

## Actual Behavior

The CJS types are specified for ESM users.
But the CJS types are for CJS, not for ESM.

## Steps to Reproduce

Should be possible to reproduce from any ESM file.

## Reproducible Demo

https://github.com/syntax-tree/hast-util-to-jsx-runtime/commit/89b9292b4ae3633a3d71adc48956521ec6d134cb

## Environment

n/a

## Extra

a) you can drop the root `types` field in `package.json`
b) generate an `esm/index.d.mts`
c) you can drop the `exports.types` fields, they are the defaults for `cjs/index.js` -> `cjs/index.d.ts`, `esm/index.mjs` -> `esm/index.d.mts`

**Comment by remarkablemark** [comment]
Thanks for opening this issue @wooorm, I opened a PR for fix #207

**Comment by vitalijalbu** [comment]
I have the same issue I think:

![Screenshot 2024-10-02 alle 07 32 58](https://github.com/user-attachments/assets/8a7a505a-1383-4976-9022-b4120dc6dcbf)

**Comment by remarkablemark** [comment]
@vitalijalbu do you mind opening a new issue?
