### ISSUE TITLE
Dynamic require of "inline-style-parser" is not supported

### ISSUE THREAD

**Issue by flvyu** [remarkablemark/style-to-object#291]
## Expected Behavior

inline-style-parser should not be dynamically required if using ESM

## Actual Behavior

ESM module is importing from CSM which results in dynamic require of inline-style-parser

## Steps to Reproduce

1. install react-markdown@^8.0.4
2. bundle react-markdown
3. run your app that uses ESM
4. observe error

## Environment

- Version: >=0.4.4<=1.0.5
- Platform: Web
- Browser: Edge
- OS: Win32

**Comment by remarkablemark** [comment]
@flvyu can you provide a reproducible example using CodeSandbox or StackBlitz?

**Comment by flvyu** [comment]
I'm trying to get a repro working. I will share once I do

**Comment by flvyu** [comment]
So it looks like the root of the issue is that the style-to-object is mixing esm and cjs. For example index.mjs (ESM) is importing StyleToObject from index.js (CJS). I was able to repro the bug which causes page to not load in this [codesandbox](https://codesandbox.io/p/devbox/wizardly-leaf-rjsn33-forked-44n8d2?workspaceId=428d1015-0b95-4b14-a740-6add24160d34&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clthr6dyn00093j6jf3wig633%2522%252C%2522sizes%2522%253A%255B76.79160005393467%252C23.208399946065327%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clthr6dym00023j6joejfenv4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clthr6dym00063j6jxnecy0kt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clthr6dyn00083j6jb7yqj5j2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B55.50210003818251%252C44.49789996181749%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clthr6dym00023j6joejfenv4%2522%253A%257B%2522id%2522%253A%2522clthr6dym00023j6joejfenv4%2522%252C%2522activeTabId%2522%253A%2522clthuixhw01vg3j6jsh50vhvg%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdist%252Findex.js%2522%252C%2522id%2522%253A%2522clthuixhw01vg3j6jsh50vhvg%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clthr6dyn00083j6jb7yqj5j2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clthr6dym00073j6jraim9prk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clthr6dyn00083j6jb7yqj5j2%2522%252C%2522activeTabId%2522%253A%2522clthr6dym00073j6jraim9prk%2522%257D%252C%2522clthr6dym00063j6jxnecy0kt%2522%253A%257B%2522id%2522%253A%2522clthr6dym00063j6jxnecy0kt%2522%252C%2522activeTabId%2522%253A%2522clthtzf9t011y3j6jkju33ve7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clthr6dym00033j6j9kvofgs8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%257D%252C%257B%2522id%2522%253A%2522clthr6dym00053j6j8lrjraiz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clthqe03n0018dcf80i992svd%2522%257D%252C%257B%2522id%2522%253A%2522clthtzf9t011y3j6jkju33ve7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clthtzfjh002sdcf87f8f3qm6%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A10%257D). 

If you also have a file that utilizes the style-to-object, you can run the following command and repro the issue

> ./esbuild src/index.tsx --bundle --external:inline-style-parser --outfile=dist/index.js

**Comment by remarkablemark** [comment]
@flvyu thanks for providing the reproducible example. I'll try to take a look this weekend.

**Comment by remarkablemark** [comment]
@flvyu I reproduced the issue in https://stackblitz.com/edit/style-to-object-291 and unfortunately there is no easy way to fix this. Even if I rewrote the library into ESM, there are dependencies that will cause the same error:

```
Uncaught Error: Dynamic require of "inline-style-parser" is not supported
```

Do you have alternatives instead of using `esbuild`?

**Comment by flvyu** [comment]
We have option to use rollup to bundle just style-to-object. By using rollup we fixed the issue.

**Comment by remarkablemark** [comment]
@flvyu Nice! That's great to hear. Closing this issue then.
